### PR TITLE
Feature/add base webservice

### LINKED ISSUE #5: Migrate MockServer to WS repo
Using the last MockServer version, we will grow using the substitution of mocked functionality by real one.

### PR DESCRIPTION
**Pull request by tokland**
Fixes #5

### CODE REVIEW

**Review by ifoche — APPROVED** [review]
Thanks @tokland

**Review by ifoche — COMMENTED** [review]
just a little question @tokland. Wouldn't you find it better to move the content of "fire" folder to the root level?

**Comment by ifoche** [comment]
Understood that we needed this in order to provide a name to the python package and import it from elsewhere. @tokland can you please add the sub-folders that disappeared from the drivers folder? Thanks!

**Comment by tokland** [comment]
Folders re-added.

**Pull request merged**
