### PR TITLE
Feature/new user request without username

### LINKED ISSUE #13: Modify NewUserRequest endpoint to allow requests without username
The NewUserRequest endpoint has to accept requests without username. The app's currently doing the call but it's receiving [a bad request failure](https://waffle.io/EyeSeeTea/FIRE-WiFiCalling/cards/59726797c18d83001a1f1896).

### PR DESCRIPTION
**Pull request by tokland**
Closes #13

### CODE REVIEW

**Review by ifoche — COMMENTED** [review]
@tokland not sure to be properly testing the issue. If I'm not bad, this PR should make newUserRequest endpoint work without needing a username. So doing a POST without any payload should create the newUserRequest. But if I understand the code, it would be waiting for a POST against newUserRequests endPoint. If I do that an exception is raised as follows:
```
Traceback (most recent call last):
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/.env/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/nacho/EyeSeeTea/code/FIRE/FIRE-WS/fire/api/server.py", line 98, in post
    new_user = request.get_json().get("user")
AttributeError: 'NoneType' object has no attribute 'get'
```

Looks like the first line...
```
new_user = request.get_json().get("user")
```
...shouldn't be there...right? Is like it's waiting for the json to contain the user, but that's not possible as we're creating a request for the admin to create a new user. Does that make sense?

**Comment by tokland** [comment]
> So doing a POST without any payload should create the newUserRequest.

The endpoint is (from https://github.com/EyeSeeTea/FIRE-MockServer/tree/development):

`POST /newUserRequests : {user: User} -> STATUS`

That's from the mockServer, it assumes the user sends some information (name, address, etc) in an object {user: User}. Does it make sense? What info does the user really sends when making a new user request?

**Comment by ifoche** [comment]
Yes...I think it makes sense, because the user will fill in [this form](https://marvelapp.com/1d00fg0/screen/18236463) and we will probable need to introduce mandatory field validation in the client to avoid sending a null request. However, would it make sense to protect us against a blank request on the WS? Maybe not...and just the traceback is enough, but as part of the validation (whenever we implement that TODO for user validation) I would also introduce a protection for this special case.

**Review by ifoche — APPROVED** [review]
Accepting the PR taking into account that the user validation should probably avoid blank requests. Thanks @tokland

**Comment by tokland** [comment]
Yes, all validations & proper error messages will be done with the final model.

**Pull request merged**
