### PR TITLE
Feature/kamailio login

### LINKED ISSUE #7: Substitute Login calls by real login
The WS must reply to login calls using Kamailio.

### PR DESCRIPTION
**Pull request by tokland**
Closes #7 (and related #9, #10)

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@tokland I cannot get it working. I've tested both in my computer and just in case it was a matter of domain misconfiguration or something like that, I also tested on dev.eyeseetea.com. But none seems to work. At the begining I thought it had to do with permissions for executing the kactl command, but when tested in my computer I even launched the server with superpowers and nothing changed...can you please take a look to dev.eyeseetea.com and tell me what's wrong there? (the consequence is an unauthorized reply on every call even if I'm sure that I'm using a valid kamailio user) Thanks in advance!

**Comment by tokland** [comment]
Can you paste the command you are running? It works for me. Are you maybe using the phone number? it's the username (we can drop it altogether if we don't need username):

```
$ curl -u joel:THEPASSWORD http://dev.eyeseetea.com:5001/currentUser
```

**Comment by ifoche** [comment]
ohhh god, I feel so dumb...yes, that was it. I was using the phoneNumber as userName. Sorry for the mistake

**Review by ifoche — APPROVED** [review]
thanks @tokland

**Comment by MurhafSousli** [comment]
@tokland Can you provide me with the username and the password because `THEPASSWORD` is not working

**Comment by ifoche** [comment]
@MurhafSousli I've sent you the usernames & passwords. I'm not writing them here because this is public. But anyway, remember that a user may be for example joel, but if its phoneNumber is 1, then it will be authenticating against kamailio with user 1, and its corresponding password. So in the app you must use, 
```
joel:<passwordForUser1InKamailio>
```

**Pull request merged**
