### PR TITLE
Feature/kamailio create user

### LINKED ISSUE #18: Create kamailio user

### PR DESCRIPTION
**Pull request by tokland**
Closes #18

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@tokland I get a 
```
configobj.DuplicateError: Duplicate keyword name at line 10.
```
I guess second one should be add_user, right?

**Comment by ifoche** [comment]
I fixed it on both normal and tests config files, but I still can't see where are we calling the add user function implemented in kamailio driver. I guess it should be called from the newUserRequest acceptance. @tokland how could I test this PR is properly working? (I see the test is not yet implemented)

**Comment by tokland** [comment]
Sorry, yes, `add_user` (I have a correct custom config file and I didn't had this error)

Yes, this PR only implements the function, it should be called at #15. 

For now, I am making only functional tests on the webserver API (with external modules -as auth- mocked), because testing Kamailio would force the user to have a running server. Do you think it's worth it and have the time to do it? (personally, I'd like to have it tested)

**Comment by ifoche** [comment]
You're right that probably it is better to move on. The code looks ok and the only way that I can imagine to decouple this code from kamailio mocking this functionality to test it works is to create a local alias to override kamctl command just to see it's being properly called, and then check that output in the test. 

Briefly...I'm approving the PR and let's see if @jordibc finds any problem while working with it in #15 :)

**Review by ifoche — APPROVED** [review]
thanks @tokland . Please @jordibc take note of the add_user function, that you probably will need in #15

**Comment by tokland** [comment]
> mocking this functionality to test it works is to create a local alias to override kamctl command

Yep, we know that's the usual compromise with testing. A "real" test of the service requires a lot of infrastructure and the "simple" mocking is not exactly trustworthy. Docker images have eased the first option, but the setup is time-consuming.

**Pull request merged**
